substitutions:
  device_name: Flexispot desk
  name: office-desk-flexispot
  unit_of_measurement: "cm" # or "in"
  min_height: "73.5"
  max_height: "123"
  ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_fallback_password: !secret ap_fallback_password
  tx_pin: GPIO17 # TXD 2
  rx_pin: GPIO16 # RXD 2
  rx_pin_keypad: GPIO3 # RX 0
  screen_pin: GPIO23
  encryption_key: !secret encryption_key

wifi:
  ssid: ${ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Fallback Hotspot
    password: ${ap_fallback_password}

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi signal"
    update_interval: 60s

packages:
  # Passthrough core (includes: keypad sensor, desk_command, virtual screen, and base core.yaml)
  core_passthrough: !include ../core/core-passthrough.yaml
